include: package:flutter_lints/flutter.yaml

formatter:
  page_width: 80
  trailing_commas: preserve

analyzer:
#   exclude:
#     - path/to/excluded/files//*

linter:
  rules:
    constant_identifier_names: false
    non_constant_identifier_names: false
    avoid_print: false
    overridden_fields: false
